### ISSUE TITLE
Tarball in the recipe directory

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/chemfiles-lib-feedstock#14]
Not sure if that is needed but it looks odd :-/

**Comment by Luthaf** [comment]
The tarball contains the [test data](https://github.com/chemfiles/tests-data/) for the code, as we can not download them during the build (the logic controlling this is here: https://github.com/chemfiles/chemfiles/blob/266ec8e34b7bcd3825e25266ee8a5ba8aa70baab/tests/CMakeLists.txt#L1-L11)

If there is another mechanism for doing this, I am open to change!

**Comment by ocefpaf** [comment]
You can fetch that using multiple sources in the recipe. Here is an example:

https://github.com/ocefpaf/proj.4-feedstock/blob/master/recipe/meta.yaml#L8-L13

**Comment by Luthaf** [comment]
Ok, I'll give it a look. It might take some time, as I am going on vacation tonight.

**Comment by ocefpaf** [comment]
Thanks! No rush.
