### ISSUE TITLE
Wrong version of libcxx pulled in

### ISSUE THREAD

**Issue by Luthaf** [conda-forge/chemfiles-lib-feedstock#27]
See https://github.com/chemfiles/chemfiles/issues/257 for the original issue report.

It looks like installing chemiles-lib does not pull in the conda-forge version of libcxx/libcxxabi on macOS. On the original issue, @richardjgowers had the standard, anaconda provided `4.0.1` version of both libraries (instead of the 8.0.0 version provided by conda-forge), leading to a crash in chemfiles.

According to https://conda-forge.org/docs/maintainer/knowledge_base.html#compilers, using `compiler('cxx')` should pull in the runtime component, does libcxx/libcxxabi works the same way? 

If not, is there any way to specify runtime dependency on the standard C++ library used when compiling the code?

Ping @conda-forge-admin

**Comment by Luthaf** [comment]
So `conda info` tells me that on osx64, chemfiles-lib depends on libcxx>=4.0.1, so that would be the culprit here.

**Comment by Luthaf** [comment]
Thinking a bit more about it, and after reading https://conda-forge.org/docs/user/tipsandtricks.html, why do you have `channel_priority: flexible` in your .condarc @richardjgowers?

**Comment by richardjgowers** [comment]
@luthaf i've never edited it manually, so it's whatever conda did after adding the channel.  It looks like flexible is the default.

**Comment by Luthaf** [comment]
So, it looks like you have `libcxx==4.0.1=h579ed51_0` installed, which is marked as broken in https://anaconda.org/conda-forge/libcxx/files. 

I also can not get #28 to work locally, since `compiler(cxx)` depends on `libcxx==4.0.1=hcfea43d_1`. (which is also marked as broken ...)

Do running `conda update libcxx` do anything for you? If not, can you try with `channel_priority: strict` instead?

**Comment by richardjgowers** [comment]
@Luthaf yeah I think updating the libcxx will fix this (not got that machine here to check), but I think more fundamentally the recipe should be smart enough to do that update for me when I (or random next user) installs chemfiles.

**Comment by Luthaf** [comment]
> more fundamentally the recipe should be smart enough to do that update for me when I (or random next user) installs chemfiles.

Yeah, I don't know how I can do that =/

@conda-forge/core Can I force a dependency on newer versions of libcxx?
