### ISSUE TITLE
How can I remove brocken build from anaconda cloud?

### ISSUE THREAD

**Issue by Luthaf** [conda-forge/chemfiles-lib-feedstock#35]
As we realized in https://github.com/MDAnalysis/mdanalysis/pull/2798, #33 had some unintentional fallout: chemfiles now uses the version of libnetcdf provided by conda-forge, butsSince the code was built with libnetcdf==4.7.4, this means the .so file it looks for is `libnetcdf.so.18`, making the code incompatible with `libnetcdf==4.6.*` which provides `libnetcdf.so.15`. To reflect this, I updated dependencies requirements in #34. 

But conda is still resolving and using the "broken" build (build number 1) from before #34. I think removing/hiding the files with build number 1 from anaconda cloud would force conda to use build number 2 or at least explicitly fail with a "can not resolve dependencies" message.

Does anyone at @conda-forge/core know how I can do this?

**Comment by isuruf** [comment]
See https://github.com/conda-forge/admin-requests

**Comment by Luthaf** [comment]
Thanks!
